# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'IntegrationTest' do

end

target 'IntegrationTestTests' do

end

target 'IntegrationTestUITests' do

end


target 'IntegrationTest-cal', exclusive: false do
    pod 'Calabash'
end
